### ISSUE TITLE
Update PHP version to 8.2

### ISSUE THREAD

**Issue by trackleft** [az-digital/azqs_module_project#13]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The default php version is 8.2

**Describe alternatives you've considered**
Do nothing.

**Additional context**
[Quickstart recently merged PHP 8.2 compatibility](https://github.com/az-digital/az_quickstart/commit/22a4232db770b75a03fa450fa59613b04148aa48)

[We've done similar things in the past](https://github.com/az-digital/azqs_module_project/commit/7c0853e67b72df48d99a53fe896f4a51e0257517)

**Comment by joeparsons** [comment]
Merged
